services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qrcodegen
    image: jpizquierdo/qrcodegen:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN